### ISSUE TITLE
30 seconds limit?

### ISSUE THREAD

**Issue by ergunkocak** [antimatter15/whammy#13]
Hi,

First of all thanks for open sourcing such useful library :)

If the recording is more than 30 seconds, video becomes problematic. The code to send video data to a preview player is : 

```
videoBlob = new Whammy.fromImageArray(frames, localframerate);
videoBlobURL = window.URL.createObjectURL(videoBlob);
document.getElementById('previewVideo');
videoElement.src = videoBlobURL;
```

I also tried updating cluster max size as (10 times more) : 

```
var CLUSTER_MAX_DURATION = 300000;
```

but this time video stuck on 32. second.

Test platform is Chrome v.36 on Mac OSX 10.9

Regards

**Comment by Jannchie** [comment]
The current version still has this problem.
