### ISSUE TITLE
last frame duration not used in video

### ISSUE THREAD

**Issue by drabinowitz** [antimatter15/whammy#28]
this is easiest to demonstrate with a one frame video:

``` javascript
var video = new Whammy.Video;
video.duration = 15000;
video.quality = 1;
//assuming here that we have an image from a canvas to use:
video.add(context);
video.compile();
```

the compiled video will have a duration of 15 seconds. But if you actually play it, the video ends instantly. You can also test this with a video with multiple frames, just make sure the frame durations are long enough that you can clearly see each frame individually, the last frame duration is never used.

**Comment by Nikaoto** [comment]
Had the same problem when compiling complex videos (with globalOpacity and lots of frames). 

The easiest workaround I've found is to just add an empty frame to the video, that way, the last part gets cut instead of the actual content you want to put in the video.

So in this case, it would be:
```javascript
var video = new Whammy.Video;
video.duration = 15000;
video.quality = 1;
//assuming here that we have an image from a canvas to use:
video.add(context);


// Fill the canvas with a black rectangle
context.fillStyle = "#000000"
context.fillRect(0, 0, context.canvas.width, context.canvas.height)
video.add(context, 1) // Doesn't matter what duration you put here, still gets cut to the first frame


video.compile();
```

**Comment by Nikaoto** [comment]
@drabinowitz  Please indicate if my solution helped you so the owner can close the issue 🙂

**Comment by drabinowitz** [comment]
ah my apologies for the delay I think this would work for me thanks a lot!
